### ISSUE TITLE
A couple typos

### ISSUE THREAD

**Issue by AndreaPi** [noamross/2017-11-14-noamross-gams-nyhackr#1]
Hi, first of all, excellent slides and thank you for releasing them! I think I found a couple typos that you may want to fix. If you prefer, I can submit a PR if you add the .Rmd to the repo.

**Page 18**

```
gam(y ~ x1 + s(x2), # model formula
data=data, # your data
family = gaussian # or something more exotic
method = "REML") # how to pick λ
```
 should be 
```
gam(y ~ x1 + s(x2), # model formula
data=data, # your data
family = gaussian, # or something more exotic
method = "REML") # how to pick λ
```
**Page 21**
maybe not an error, but according to `te` help, the right way to write a functional ANOVA formula shouldn't be

`y ~ ti(x1) + ti(x2) + ti(x1, x2)`

rather than 

`y ~ te(x1) + te(x2) + ti(x1, x2)`?

**Page 41**

The first response variable is `category`, but isn't the second response variable missing in both examples? 

--------
Don't get me wrong -- I know it's a presentation and not literate programming, so you're not expected to be able to run the code as it is, but I thought this would help make the presentation even more readable.

**Comment by gavinsimpson** [comment]
Re the single penalty `te()` terms; this is now an error (or should be from reading the Changelog). V 1.8-19 has this entry:

> * single penalty tensor product smooths removed (previously deprecated).

Re the `multinom` model, the code is right; you only need to specify the response for the first linear predictor (assumption is that ordering of levels counts).

For the `mvn` you need to specify the *n* variables that form the multivariate response via separate LHS.
